### ISSUE TITLE
question: why have to ssh onto the server ?

### ISSUE THREAD

**Issue by zinking** [gipmon/python-ssh-mysqldump-dropbox#1]
can't the work be done over the vm? why bother ssh to the remote machine?

I guess it also could be done there?

**Comment by rafaelferreirapt** [comment]
Don't forget that you my have an environment that you have a master that is responsible to backup two or more servers that are slaves and those servers have MySQL databases. It's scalable. [Master slave architecture](http://www.dossier-andreas.net/software_architecture/masterslave.jpg).
